env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-ignore: allow-with-description
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-unused-vars-experimental':
    - error
    - ignoredNamesRegex: ^_
